version: "3.9"

services:
  mongo:
    image: mongo:6
    container_name: mongo
    volumes:
      - mongo-data:/data/db

  backend:
    container_name: backend
    build:
      context: ./backend
    environment:
      - PORT=8001
      - MONGO_URI=mongodb://mongo:27017/todo
    depends_on:
      - mongo
    expose:
      - "8001"

  frontend:
    container_name: nginx
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mongo-data:

